apiVersion: v1
kind: Secret
metadata:
  name: coolify-secrets
type: Opaque
stringData:
  DB_PASSWORD: {{ .Values.secrets.DB_PASSWORD }}
  REDIS_PASSWORD: {{ .Values.secrets.REDIS_PASSWORD }}

  PUSHER_APP_ID: {{ .Values.secrets.PUSHER_APP_ID }}
  PUSHER_APP_KEY: {{ .Values.secrets.PUSHER_APP_KEY }}
  PUSHER_APP_SECRET: {{ .Values.secrets.PUSHER_APP_SECRET }}
  APP_ID: {{ .Values.secrets.APP_ID }}
  APP_KEY: {{ .Values.secrets.APP_KEY }}

